#!/usr/bin/env python3

import subprocess
import sys

def main():
    # Run the Python build script
    subprocess.run(["python3", "build_list.py"], check=True)
    
    # Format with Deno
    subprocess.run(["deno", "fmt", "."], check=True)
    
    # Git add all changes
    subprocess.run(["git", "add", "."], check=True)
    
    # Git commit with message from command line argument
    if len(sys.argv) > 1:
        commit_message = sys.argv[1]
        subprocess.run(["git", "commit", "-m", commit_message], check=True)
    else:
        print("Please provide a commit message")
        sys.exit(1)
    
    # Git push
    subprocess.run(["git", "push"], check=True)

if __name__ == "__main__":
    main()